ru: [а, б, в, г, д, е, ё, ж, з, и, й, к, л, м, н, о, п, р, с, т, у, ф, х, ц, ч, ш, щ, ъ, ы, ь, э, ю, я]
en: [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z]
de: [a, ä, b, c, d, e, f, g, h, i, j, k, l, m, n, o, ö, p, q, r, s, ß, t, u, ü, v, w, x, y, z]
es: [a, á , b, c, d, e, é, f, g, h, i, í, j, k, l, m, n, ñ, o, ó, p, q, r, s, t, u, ú, ü, v, w, x, y, z, ¿, ¡]
