require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Users::CoursesController do

  # This should return the minimal set of attributes required to create a valid
  # Users::Course. As you add validations to Users::Course, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "slug" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Users::CoursesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all users_courses as @users_courses" do
      course = Users::Course.create! valid_attributes
      get :index, {}, valid_session
      assigns(:users_courses).should eq([course])
    end
  end

  describe "GET show" do
    it "assigns the requested users_course as @users_course" do
      course = Users::Course.create! valid_attributes
      get :show, {:id => course.to_param}, valid_session
      assigns(:users_course).should eq(course)
    end
  end

  describe "GET new" do
    it "assigns a new users_course as @users_course" do
      get :new, {}, valid_session
      assigns(:users_course).should be_a_new(Users::Course)
    end
  end

  describe "GET edit" do
    it "assigns the requested users_course as @users_course" do
      course = Users::Course.create! valid_attributes
      get :edit, {:id => course.to_param}, valid_session
      assigns(:users_course).should eq(course)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Users::Course" do
        expect {
          post :create, {:users_course => valid_attributes}, valid_session
        }.to change(Users::Course, :count).by(1)
      end

      it "assigns a newly created users_course as @users_course" do
        post :create, {:users_course => valid_attributes}, valid_session
        assigns(:users_course).should be_a(Users::Course)
        assigns(:users_course).should be_persisted
      end

      it "redirects to the created users_course" do
        post :create, {:users_course => valid_attributes}, valid_session
        response.should redirect_to(Users::Course.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved users_course as @users_course" do
        # Trigger the behavior that occurs when invalid params are submitted
        Users::Course.any_instance.stub(:save).and_return(false)
        post :create, {:users_course => { "slug" => "invalid value" }}, valid_session
        assigns(:users_course).should be_a_new(Users::Course)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Users::Course.any_instance.stub(:save).and_return(false)
        post :create, {:users_course => { "slug" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested users_course" do
        course = Users::Course.create! valid_attributes
        # Assuming there are no other users_courses in the database, this
        # specifies that the Users::Course created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Users::Course.any_instance.should_receive(:update_attributes).with({ "slug" => "MyString" })
        put :update, {:id => course.to_param, :users_course => { "slug" => "MyString" }}, valid_session
      end

      it "assigns the requested users_course as @users_course" do
        course = Users::Course.create! valid_attributes
        put :update, {:id => course.to_param, :users_course => valid_attributes}, valid_session
        assigns(:users_course).should eq(course)
      end

      it "redirects to the users_course" do
        course = Users::Course.create! valid_attributes
        put :update, {:id => course.to_param, :users_course => valid_attributes}, valid_session
        response.should redirect_to(course)
      end
    end

    describe "with invalid params" do
      it "assigns the users_course as @users_course" do
        course = Users::Course.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Users::Course.any_instance.stub(:save).and_return(false)
        put :update, {:id => course.to_param, :users_course => { "slug" => "invalid value" }}, valid_session
        assigns(:users_course).should eq(course)
      end

      it "re-renders the 'edit' template" do
        course = Users::Course.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Users::Course.any_instance.stub(:save).and_return(false)
        put :update, {:id => course.to_param, :users_course => { "slug" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested users_course" do
      course = Users::Course.create! valid_attributes
      expect {
        delete :destroy, {:id => course.to_param}, valid_session
      }.to change(Users::Course, :count).by(-1)
    end

    it "redirects to the users_courses list" do
      course = Users::Course.create! valid_attributes
      delete :destroy, {:id => course.to_param}, valid_session
      response.should redirect_to(users_courses_url)
    end
  end

end
